# Generated by Django 4.2.7 on 2025-12-18 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Design', max_length=255)),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('normal_image', models.ImageField(blank=True, null=True, upload_to='designs/normal/')),
                ('embroidery_preview', models.ImageField(blank=True, null=True, upload_to='designs/embroidery/')),
                ('prompt', models.TextField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('text_content', models.CharField(blank=True, max_length=500, null=True)),
                ('text_font', models.CharField(default='Inter', max_length=100)),
                ('text_style', models.CharField(default='Bold', max_length=50)),
                ('thread_colors', models.JSONField(blank=True, default=list)),
                ('stitch_density', models.CharField(default='High', max_length=20)),
                ('auto_trim', models.BooleanField(default=True)),
                ('canvas_width', models.IntegerField(default=1200)),
                ('canvas_height', models.IntegerField(default=1200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('processing', 'Processing'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tokens', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_token', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('savings_percentage', models.IntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.IntegerField(default=0)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'Usage'), ('refund', 'Refund'), ('welcome_bonus', 'Welcome Bonus')], max_length=20)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='submitted', max_length=20)),
                ('tokens_used', models.IntegerField(default=2)),
                ('output_dst', models.FileField(blank=True, null=True, upload_to='orders/output/')),
                ('output_pes', models.FileField(blank=True, null=True, upload_to='orders/output/')),
                ('output_jef', models.FileField(blank=True, null=True, upload_to='orders/output/')),
                ('output_exp', models.FileField(blank=True, null=True, upload_to='orders/output/')),
                ('output_vp3', models.FileField(blank=True, null=True, upload_to='orders/output/')),
                ('output_xxx', models.FileField(blank=True, null=True, upload_to='orders/output/')),
                ('email_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.design')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.design')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'design')},
            },
        ),
    ]
