# Generated by Django 4.2.7 on 2025-12-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='embroidery_preview',
            new_name='embroidery_preview_url',
        ),
        migrations.RemoveField(
            model_name='design',
            name='normal_image',
        ),
        migrations.AddField(
            model_name='design',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='designs/normal/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tokens',
            field=models.IntegerField(default=5),
        ),
    ]
