# Generated by Django 4.2.7 on 2025-12-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_design_image_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='embroidery_preview_url',
            new_name='embroidery_preview',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='image_url',
            new_name='normal_image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
