# Generated by Django 4.2.7 on 2025-12-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_embroidery_preview_url_design_embroidery_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_formats',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
