# Generated by Django 4.2.7 on 2025-12-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_requested_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='output_10o',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_cmd',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_ds9',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_dsb',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_dsz',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_emt',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_fdr',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_hus',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_pec',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_sew',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_stx',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_tap',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_tbf',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_tim',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
        migrations.AddField(
            model_name='order',
            name='output_vip',
            field=models.FileField(blank=True, null=True, upload_to='orders/output/'),
        ),
    ]
