# Generated by Django 4.2.7 on 2025-12-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_convert_stitch_density'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('tokens_required', models.IntegerField(default=10)),
                ('category', models.CharField(choices=[('text', 'Text Customization'), ('color', 'Color Options'), ('effect', 'Special Effects'), ('quality', 'Quality Enhancement'), ('rush', 'Rush Processing'), ('support', 'Premium Support')], default='effect', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('icon_emoji', models.CharField(default='✨', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignFeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_spent', models.IntegerField()),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usages', to='api.design')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.designfeature')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='designfeature',
            index=models.Index(fields=['is_active'], name='api_designf_is_acti_d0ece0_idx'),
        ),
        migrations.AddIndex(
            model_name='designfeature',
            index=models.Index(fields=['category'], name='api_designf_categor_571225_idx'),
        ),
        migrations.AddIndex(
            model_name='designfeatureusage',
            index=models.Index(fields=['design'], name='api_designf_design__336fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='designfeatureusage',
            index=models.Index(fields=['feature'], name='api_designf_feature_74a3ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designfeatureusage',
            unique_together={('design', 'feature')},
        ),
    ]
