# Generated by Django 4.2.7 on 2025-12-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_designfeature_designfeatureusage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCostSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_image_generation', models.IntegerField(default=2, help_text='Tokens cost for generating AI images')),
                ('order_placement', models.IntegerField(default=1, help_text='Tokens cost for placing an order')),
                ('embroidery_preview', models.IntegerField(default=1, help_text='Tokens cost for embroidery preview')),
                ('text_addition', models.IntegerField(default=1, help_text='Tokens cost for adding text to designs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Token Cost Settings',
            },
        ),
    ]
