# Generated by Django 4.2.7 on 2025-12-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tokencostsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbroiderySizePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_cm', models.IntegerField(help_text='Embroidery size in centimeters', unique=True)),
                ('price_in_tokens', models.IntegerField(help_text='Token cost for this size')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Embroidery Size Pricing',
                'verbose_name_plural': 'Embroidery Size Pricing',
                'ordering': ['size_cm'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='embroidery_size_cm',
            field=models.IntegerField(default=10, help_text='Embroidery size in centimeters (5-40 cm)'),
        ),
        migrations.AddField(
            model_name='order',
            name='embroidery_size_cm',
            field=models.IntegerField(default=10, help_text='Embroidery size in centimeters (5-40 cm)'),
        ),
    ]
