# Generated by Django 4.2.7 on 2025-12-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_embroiderysizepricing_cart_embroidery_size_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='embroidery_size_cm',
            field=models.IntegerField(default=10, help_text='Embroidery size in centimeters (5-40 cm)'),
        ),
    ]
