# Generated by Django 5.1.5 on 2026-02-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='machine_brand',
            field=models.CharField(blank=True, help_text="Customer's embroidery machine brand", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='requested_format',
            field=models.CharField(blank=True, help_text="Customer's preferred file format (pes, exp, jef, etc.)", max_length=10, null=True),
        ),
    ]
